spring.application.name=frontend

# Server Configuration
server.port=8081

# Backend API URL
BACKEND_API_URL=http://localhost:8080/api

# Thymeleaf Configuration
spring.thymeleaf.cache=false
spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.suffix=.html
